samtools index lz-1.rmdup.bam
samtools index lz-10.rmdup.bam
samtools index lz-100.rmdup.bam
samtools index lz-101.rmdup.bam
samtools index lz-102.rmdup.bam
samtools index lz-103.rmdup.bam
samtools index lz-104.rmdup.bam
samtools index lz-105.rmdup.bam
samtools index lz-106.rmdup.bam
samtools index lz-107.rmdup.bam
samtools index lz-108.rmdup.bam
samtools index lz-109.rmdup.bam
samtools index lz-11.rmdup.bam
samtools index lz-110.rmdup.bam
samtools index lz-111.rmdup.bam
samtools index lz-112.rmdup.bam
samtools index lz-113.rmdup.bam
samtools index lz-114.rmdup.bam
samtools index lz-115.rmdup.bam
samtools index lz-116.rmdup.bam
samtools index lz-117.rmdup.bam
samtools index lz-118.rmdup.bam
samtools index lz-119.rmdup.bam
samtools index lz-12.rmdup.bam
samtools index lz-120.rmdup.bam
samtools index lz-121.rmdup.bam
samtools index lz-122.rmdup.bam
samtools index lz-123.rmdup.bam
samtools index lz-124.rmdup.bam
samtools index lz-125.rmdup.bam
samtools index lz-126.rmdup.bam
samtools index lz-127.rmdup.bam
samtools index lz-128.rmdup.bam
samtools index lz-129.rmdup.bam
samtools index lz-13.rmdup.bam
samtools index lz-130.rmdup.bam
samtools index lz-131.rmdup.bam
samtools index lz-132.rmdup.bam
samtools index lz-133.rmdup.bam
samtools index lz-134.rmdup.bam
samtools index lz-135.rmdup.bam
samtools index lz-136.rmdup.bam
samtools index lz-137.rmdup.bam
samtools index lz-138.rmdup.bam
samtools index lz-14.rmdup.bam
samtools index lz-140.rmdup.bam
samtools index lz-141.rmdup.bam
samtools index lz-142.rmdup.bam
samtools index lz-143.rmdup.bam
samtools index lz-144.rmdup.bam
samtools index lz-145.rmdup.bam
samtools index lz-146.rmdup.bam
samtools index lz-147.rmdup.bam
samtools index lz-148.rmdup.bam
samtools index lz-149.rmdup.bam
samtools index lz-15.rmdup.bam
samtools index lz-150.rmdup.bam
samtools index lz-151.rmdup.bam
samtools index lz-152.rmdup.bam
samtools index lz-153.rmdup.bam
samtools index lz-154.rmdup.bam
samtools index lz-155.rmdup.bam
samtools index lz-156.rmdup.bam
samtools index lz-157.rmdup.bam
samtools index lz-158.rmdup.bam
samtools index lz-159.rmdup.bam
samtools index lz-16.rmdup.bam
samtools index lz-160.rmdup.bam
samtools index lz-161.rmdup.bam
samtools index lz-162.rmdup.bam
samtools index lz-163.rmdup.bam
samtools index lz-164.rmdup.bam
samtools index lz-165.rmdup.bam
samtools index lz-166.rmdup.bam
samtools index lz-167.rmdup.bam
samtools index lz-168.rmdup.bam
samtools index lz-169.rmdup.bam
samtools index lz-17.rmdup.bam
samtools index lz-170.rmdup.bam
samtools index lz-171.rmdup.bam
