samtools index lz-1.rmdup.bam
samtools index lz-10.rmdup.bam
samtools index lz-100.rmdup.bam
samtools index lz-101.rmdup.bam
samtools index lz-102.rmdup.bam
samtools index lz-103.rmdup.bam
samtools index lz-104.rmdup.bam
samtools index lz-105.rmdup.bam
samtools index lz-106.rmdup.bam
samtools index lz-107.rmdup.bam
samtools index lz-108.rmdup.bam
samtools index lz-109.rmdup.bam
samtools index lz-11.rmdup.bam
samtools index lz-110.rmdup.bam
samtools index lz-111.rmdup.bam
samtools index lz-112.rmdup.bam
samtools index lz-113.rmdup.bam
samtools index lz-114.rmdup.bam
samtools index lz-115.rmdup.bam
samtools index lz-116.rmdup.bam
samtools index lz-117.rmdup.bam
samtools index lz-118.rmdup.bam
samtools index lz-119.rmdup.bam
samtools index lz-12.rmdup.bam
samtools index lz-120.rmdup.bam
samtools index lz-121.rmdup.bam
samtools index lz-122.rmdup.bam
samtools index lz-123.rmdup.bam
samtools index lz-124.rmdup.bam
samtools index lz-125.rmdup.bam
samtools index lz-126.rmdup.bam
samtools index lz-127.rmdup.bam
samtools index lz-128.rmdup.bam
samtools index lz-129.rmdup.bam
samtools index lz-13.rmdup.bam
samtools index lz-130.rmdup.bam
samtools index lz-131.rmdup.bam
samtools index lz-132.rmdup.bam
samtools index lz-133.rmdup.bam
samtools index lz-134.rmdup.bam
samtools index lz-135.rmdup.bam
samtools index lz-136.rmdup.bam
samtools index lz-137.rmdup.bam
samtools index lz-138.rmdup.bam
samtools index lz-14.rmdup.bam
samtools index lz-140.rmdup.bam
samtools index lz-141.rmdup.bam
samtools index lz-142.rmdup.bam
samtools index lz-143.rmdup.bam
samtools index lz-144.rmdup.bam
samtools index lz-145.rmdup.bam
samtools index lz-146.rmdup.bam
samtools index lz-147.rmdup.bam
samtools index lz-148.rmdup.bam
samtools index lz-149.rmdup.bam
samtools index lz-15.rmdup.bam
samtools index lz-150.rmdup.bam
samtools index lz-151.rmdup.bam
samtools index lz-152.rmdup.bam
samtools index lz-153.rmdup.bam
samtools index lz-154.rmdup.bam
samtools index lz-155.rmdup.bam
samtools index lz-156.rmdup.bam
samtools index lz-157.rmdup.bam
samtools index lz-158.rmdup.bam
samtools index lz-159.rmdup.bam
samtools index lz-16.rmdup.bam
samtools index lz-160.rmdup.bam
samtools index lz-161.rmdup.bam
samtools index lz-162.rmdup.bam
samtools index lz-163.rmdup.bam
samtools index lz-164.rmdup.bam
samtools index lz-165.rmdup.bam
samtools index lz-166.rmdup.bam
samtools index lz-167.rmdup.bam
samtools index lz-168.rmdup.bam
samtools index lz-169.rmdup.bam
samtools index lz-17.rmdup.bam
samtools index lz-170.rmdup.bam
samtools index lz-171.rmdup.bam
samtools index lz-172.rmdup.bam
samtools index lz-173.rmdup.bam
samtools index lz-174.rmdup.bam
samtools index lz-175.rmdup.bam
samtools index lz-176.rmdup.bam
samtools index lz-177.rmdup.bam
samtools index lz-178.rmdup.bam
samtools index lz-179.rmdup.bam
samtools index lz-18.rmdup.bam
samtools index lz-180.rmdup.bam
samtools index lz-181.rmdup.bam
samtools index lz-182.rmdup.bam
samtools index lz-183.rmdup.bam
samtools index lz-184.rmdup.bam
samtools index lz-185.rmdup.bam
samtools index lz-186.rmdup.bam
samtools index lz-187.rmdup.bam
samtools index lz-188.rmdup.bam
samtools index lz-189.rmdup.bam
samtools index lz-19.rmdup.bam
samtools index lz-190.rmdup.bam
samtools index lz-191.rmdup.bam
samtools index lz-192.rmdup.bam
samtools index lz-193.rmdup.bam
samtools index lz-194.rmdup.bam
samtools index lz-195.rmdup.bam
samtools index lz-196.rmdup.bam
samtools index lz-197.rmdup.bam
samtools index lz-198.rmdup.bam
samtools index lz-199.rmdup.bam
samtools index lz-2.rmdup.bam
samtools index lz-20.rmdup.bam
samtools index lz-200.rmdup.bam
samtools index lz-201.rmdup.bam
samtools index lz-202.rmdup.bam
samtools index lz-203.rmdup.bam
samtools index lz-204.rmdup.bam
samtools index lz-205.rmdup.bam
samtools index lz-206.rmdup.bam
samtools index lz-207.rmdup.bam
samtools index lz-208.rmdup.bam
samtools index lz-209.rmdup.bam
samtools index lz-21.rmdup.bam
samtools index lz-210.rmdup.bam
samtools index lz-211.rmdup.bam
samtools index lz-212.rmdup.bam
samtools index lz-213.rmdup.bam
samtools index lz-214.rmdup.bam
samtools index lz-215.rmdup.bam
samtools index lz-216.rmdup.bam
samtools index lz-217.rmdup.bam
samtools index lz-218.rmdup.bam
samtools index lz-219.rmdup.bam
samtools index lz-22.rmdup.bam
samtools index lz-23.rmdup.bam
samtools index lz-24.rmdup.bam
samtools index lz-25.rmdup.bam
samtools index lz-26.rmdup.bam
samtools index lz-27.rmdup.bam
samtools index lz-28.rmdup.bam
samtools index lz-29.rmdup.bam
samtools index lz-3.rmdup.bam
samtools index lz-30.rmdup.bam
samtools index lz-32.rmdup.bam
samtools index lz-33.rmdup.bam
samtools index lz-34.rmdup.bam
samtools index lz-35.rmdup.bam
samtools index lz-36.rmdup.bam
samtools index lz-37.rmdup.bam
samtools index lz-38.rmdup.bam
samtools index lz-39.rmdup.bam
samtools index lz-4.rmdup.bam
samtools index lz-40.rmdup.bam
samtools index lz-41.rmdup.bam
samtools index lz-42.rmdup.bam
samtools index lz-43.rmdup.bam
samtools index lz-44.rmdup.bam
samtools index lz-45.rmdup.bam
samtools index lz-46.rmdup.bam
samtools index lz-47.rmdup.bam
samtools index lz-48.rmdup.bam
samtools index lz-49.rmdup.bam
samtools index lz-5.rmdup.bam
samtools index lz-50.rmdup.bam
samtools index lz-51.rmdup.bam
samtools index lz-52.rmdup.bam
samtools index lz-53.rmdup.bam
samtools index lz-54.rmdup.bam
samtools index lz-55.rmdup.bam
samtools index lz-56.rmdup.bam
samtools index lz-57.rmdup.bam
samtools index lz-58.rmdup.bam
samtools index lz-59.rmdup.bam
samtools index lz-6.rmdup.bam
samtools index lz-60.rmdup.bam
samtools index lz-61.rmdup.bam
samtools index lz-62.rmdup.bam
samtools index lz-63.rmdup.bam
samtools index lz-64.rmdup.bam
samtools index lz-65.rmdup.bam
samtools index lz-66.rmdup.bam
samtools index lz-67.rmdup.bam
samtools index lz-68.rmdup.bam
samtools index lz-69.rmdup.bam
samtools index lz-7.rmdup.bam
samtools index lz-70.rmdup.bam
samtools index lz-71.rmdup.bam
samtools index lz-72.rmdup.bam
samtools index lz-73.rmdup.bam
samtools index lz-74.rmdup.bam
samtools index lz-75.rmdup.bam
samtools index lz-76.rmdup.bam
samtools index lz-77.rmdup.bam
samtools index lz-78.rmdup.bam
samtools index lz-79.rmdup.bam
samtools index lz-8.rmdup.bam
samtools index lz-80.rmdup.bam
samtools index lz-81.rmdup.bam
samtools index lz-82.rmdup.bam
samtools index lz-83.rmdup.bam
samtools index lz-84.rmdup.bam
samtools index lz-85.rmdup.bam
samtools index lz-86.rmdup.bam
samtools index lz-87.rmdup.bam
samtools index lz-88.rmdup.bam
samtools index lz-89.rmdup.bam
samtools index lz-9.rmdup.bam
samtools index lz-90.rmdup.bam
samtools index lz-91.rmdup.bam
samtools index lz-92.rmdup.bam
samtools index lz-93.rmdup.bam
samtools index lz-94.rmdup.bam
samtools index lz-95.rmdup.bam
samtools index lz-96.rmdup.bam
samtools index lz-97.rmdup.bam
samtools index lz-98.rmdup.bam
samtools index lz-99.rmdup.bam
