/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_RNASeq-reads/Mung_091DL-2-I_1.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_RNASeq-reads/Mung_091DL-2-I_2.fq.gz 2>Mung_091DL-2-I.mapstat > Mung_091DL-2-I.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 Mung_091DL-2-I.nosort.bam > Mung_091DL-2-I.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_RNASeq-reads/Mung_091DL-7-I_1.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_RNASeq-reads/Mung_091DL-7-I_2.fq.gz 2>Mung_091DL-7-I.mapstat > Mung_091DL-7-I.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 Mung_091DL-7-I.nosort.bam > Mung_091DL-7-I.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_RNASeq-reads/Mung_DL-3-I_1.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_RNASeq-reads/Mung_DL-3-I_2.fq.gz 2>Mung_DL-3-I.mapstat > Mung_DL-3-I.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 Mung_DL-3-I.nosort.bam > Mung_DL-3-I.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_1_1.clean.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_1_2.clean.fq.gz 2>JL7_1.mapstat >JL7_1.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 JL7_1.nosort.bam > JL7_1.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_2_1.clean.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_2_2.clean.fq.gz 2>JL7_2.mapstat >JL7_2.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 JL7_2.nosort.bam > JL7_2.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_3_1.clean.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_3_2.clean.fq.gz 2>JL7_3.mapstat >JL7_3.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 JL7_3.nosort.bam > JL7_3.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_SE_1_1.clean.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_SE_1_2.clean.fq.gz 2>JL7_SE_1.mapstat >JL7_SE_1.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 JL7_SE_1.nosort.bam > JL7_SE_1.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_SE_2_1.clean.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_SE_2_2.clean.fq.gz 2>JL7_SE_2.mapstat >JL7_SE_2.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 JL7_SE_2.nosort.bam > JL7_SE_2.bam
/data/software/soft/hisat2-2.1.0/hisat2 -p 8 --dta -x /project/fujun/01.assembly/05.latest_ref/vigna_radiata.genome.fa -1 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_SE_3_1.clean.fq.gz -2 /project/pengjx/rawdata/RNAseq/mungbean_flower_RNAseq_cleandata/JL7_SE_3_2.clean.fq.gz 2>JL7_SE_3.mapstat >JL7_SE_3.nosort.bam ;/data/software/miniconda2/envs/masurca/bin/samtools sort -@ 8 JL7_SE_3.nosort.bam > JL7_SE_3.bam
