delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-10.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-10.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-100.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-100.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-101.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-101.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-102.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-102.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-103.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-103.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-104.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-104.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-105.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-105.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-106.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-106.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-107.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-107.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-108.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-108.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-109.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-109.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-11.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-11.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-110.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-110.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-111.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-111.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-112.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-112.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-113.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-113.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-114.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-114.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-115.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-115.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-116.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-116.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-117.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-117.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-118.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-118.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-119.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-119.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-12.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-12.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-120.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-120.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-121.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-121.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-122.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-122.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-123.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-123.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-124.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-124.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-125.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-125.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-126.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-126.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-127.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-127.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-128.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-128.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-129.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-129.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-13.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-13.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-130.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-130.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-131.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-131.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-132.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-132.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-133.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-133.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-134.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-134.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-135.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-135.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-136.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-136.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-137.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-137.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-138.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-138.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-14.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-14.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-140.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-140.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-141.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-141.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-142.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-142.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-143.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-143.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-144.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-144.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-145.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-145.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-146.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-146.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-147.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-147.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-148.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-148.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-149.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-149.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-15.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-15.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-150.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-150.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-151.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-151.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-152.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-152.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-153.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-153.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-154.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-154.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-155.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-155.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-156.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-156.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-157.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-157.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-158.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-158.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-159.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-159.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-16.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-16.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-160.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-160.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-161.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-161.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-162.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-162.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-163.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-163.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-164.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-164.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-165.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-165.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-166.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-166.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-167.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-167.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-168.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-168.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-169.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-169.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-17.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-17.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-170.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-170.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-171.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-171.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-172.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-172.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-173.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-173.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-174.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-174.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-175.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-175.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-176.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-176.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-177.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-177.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-178.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-178.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-179.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-179.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-18.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-18.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-180.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-180.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-181.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-181.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-182.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-182.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-183.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-183.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-184.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-184.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-185.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-185.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-186.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-186.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-187.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-187.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-188.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-188.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-189.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-189.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-19.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-19.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-190.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-190.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-191.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-191.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-192.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-192.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-193.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-193.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-194.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-194.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-195.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-195.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-196.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-196.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-197.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-197.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-198.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-198.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-199.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-199.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-2.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-2.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-20.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-20.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-200.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-200.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-201.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-201.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-202.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-202.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-203.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-203.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-204.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-204.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-205.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-205.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-206.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-206.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-207.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-207.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-208.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-208.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-209.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-209.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-21.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-21.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-210.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-210.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-211.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-211.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-212.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-212.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-213.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-213.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-214.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-214.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-215.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-215.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-216.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-216.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-217.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-217.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-218.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-218.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-219.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-219.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-22.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-22.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-23.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-23.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-24.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-24.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-25.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-25.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-26.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-26.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-27.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-27.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-28.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-28.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-29.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-29.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-3.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-3.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-30.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-30.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-32.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-32.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-33.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-33.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-34.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-34.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-35.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-35.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-36.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-36.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-37.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-37.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-38.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-38.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-39.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-39.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-4.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-4.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-40.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-40.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-41.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-41.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-42.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-42.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-43.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-43.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-44.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-44.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-45.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-45.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-46.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-46.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-47.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-47.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-48.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-48.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-49.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-49.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-5.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-5.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-50.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-50.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-51.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-51.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-52.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-52.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-53.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-53.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-54.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-54.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-55.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-55.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-56.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-56.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-57.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-57.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-58.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-58.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-59.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-59.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-6.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-6.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-60.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-60.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-61.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-61.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-62.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-62.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-63.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-63.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-64.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-64.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-65.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-65.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-66.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-66.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-67.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-67.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-68.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-68.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-69.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-69.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-7.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-7.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-70.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-70.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-71.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-71.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-72.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-72.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-73.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-73.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-74.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-74.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-75.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-75.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-76.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-76.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-77.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-77.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-78.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-78.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-79.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-79.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-8.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-8.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-80.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-80.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-81.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-81.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-82.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-82.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-83.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-83.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-84.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-84.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-85.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-85.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-86.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-86.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-87.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-87.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-88.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-88.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-89.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-89.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-9.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-9.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-90.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-90.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-91.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-91.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-92.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-92.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-93.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-93.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-94.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-94.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-95.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-95.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-96.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-96.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-97.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-97.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-98.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-98.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -o lz-99.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-99.rmdup.bam
