delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-10.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-10.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-100.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-100.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-101.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-101.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-102.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-102.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-103.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-103.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-104.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-104.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-105.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-105.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-106.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-106.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-107.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-107.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-108.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-108.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-109.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-109.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-11.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-11.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-110.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-110.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-111.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-111.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-112.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-112.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-113.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-113.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-114.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-114.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-115.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-115.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-116.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-116.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-117.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-117.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-118.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-118.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-119.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-119.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-12.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-12.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-120.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-120.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-121.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-121.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-122.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-122.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-123.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-123.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-124.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-124.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-125.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-125.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-126.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-126.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-127.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-127.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-128.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-128.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-129.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-129.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-13.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-13.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-130.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-130.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-131.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-131.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-132.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-132.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-133.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-133.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-134.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-134.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-135.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-135.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-136.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-136.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-137.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-137.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-138.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-138.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-14.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-14.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-140.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-140.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-141.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-141.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-142.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-142.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-143.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-143.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-144.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-144.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-145.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-145.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-146.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-146.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-147.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-147.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-148.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-148.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-149.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-149.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-15.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-15.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-150.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-150.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-151.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-151.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-152.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-152.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-153.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-153.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-154.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-154.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-155.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-155.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-156.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-156.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-157.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-157.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-158.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-158.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-159.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-159.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-16.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-16.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-160.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-160.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-161.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-161.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-162.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-162.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-163.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-163.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-164.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-164.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-165.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-165.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-166.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-166.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-167.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-167.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-168.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-168.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-169.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-169.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-17.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-17.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-170.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-170.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-171.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-171.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-172.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-172.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-173.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-173.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-174.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-174.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-175.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-175.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-176.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-176.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-177.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-177.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-178.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-178.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-179.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-179.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-18.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-18.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-180.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-180.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-181.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-181.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-182.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-182.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-183.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-183.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-184.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-184.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-185.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-185.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-186.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-186.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-187.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-187.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-188.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-188.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-189.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-189.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-19.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-19.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-190.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-190.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-191.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-191.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-192.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-192.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-193.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-193.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-194.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-194.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-195.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-195.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-196.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-196.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-197.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-197.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-198.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-198.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-199.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-199.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-2.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-2.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-20.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-20.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-200.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-200.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-201.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-201.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-202.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-202.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-203.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-203.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-204.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-204.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-205.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-205.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-206.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-206.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-207.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-207.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-208.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-208.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-209.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-209.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-21.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-21.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-210.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-210.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-211.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-211.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-212.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-212.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-213.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-213.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-214.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-214.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-215.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-215.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-216.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-216.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-217.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-217.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-218.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-218.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-219.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-219.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-22.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-22.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-23.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-23.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-24.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-24.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-25.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-25.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-26.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-26.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-27.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-27.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-28.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-28.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-29.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-29.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-3.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-3.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-30.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-30.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-32.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-32.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-33.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-33.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-34.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-34.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-35.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-35.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-36.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-36.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-37.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-37.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-38.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-38.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-39.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-39.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-4.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-4.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-40.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-40.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-41.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-41.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-42.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-42.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-43.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-43.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-44.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-44.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-45.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-45.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-46.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-46.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-47.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-47.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-48.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-48.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-49.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-49.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-5.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-5.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-50.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-50.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-51.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-51.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-52.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-52.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-53.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-53.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-54.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-54.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-55.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-55.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-56.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-56.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-57.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-57.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-58.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-58.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-59.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-59.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-6.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-6.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-60.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-60.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-61.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-61.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-62.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-62.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-63.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-63.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-64.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-64.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-65.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-65.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-66.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-66.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-67.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-67.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-68.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-68.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-69.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-69.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-7.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-7.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-70.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-70.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-71.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-71.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-72.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-72.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-73.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-73.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-74.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-74.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-75.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-75.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-76.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-76.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-77.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-77.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-78.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-78.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-79.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-79.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-8.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-8.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-80.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-80.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-81.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-81.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-82.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-82.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-83.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-83.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-84.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-84.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-85.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-85.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-86.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-86.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-87.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-87.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-88.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-88.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-89.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-89.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-9.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-9.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-90.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-90.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-91.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-91.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-92.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-92.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-93.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-93.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-94.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-94.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-95.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-95.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-96.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-96.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-97.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-97.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-98.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-98.rmdup.bam
delly call -g /project/pengjx/mungbean/00.genome/vigna_radiata.genome.fa -v ../02.merge/sites.bcf -o lz-99.geno.bcf /project/pengjx/mungbean/01.callvcf/gwas/bam/lz-99.rmdup.bam
